/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppGiftRouteImport } from './routes/_app/gift'
import { Route as AppOrderRouteImport } from './routes/_app/order'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppStoresRouteImport } from './routes/_app/stores'
import { Route as AppOrderIdRouteImport } from './routes/_app/order.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppGiftRoute = AppGiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderRoute = AppOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderIdRoute = AppOrderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrderRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/gift': typeof AppGiftRoute
  '/order': typeof AppOrderRouteWithChildren
  '/scan': typeof AppScanRoute
  '/stores': typeof AppStoresRoute
  '/order/$id': typeof AppOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/gift': typeof AppGiftRoute
  '/order': typeof AppOrderRouteWithChildren
  '/scan': typeof AppScanRoute
  '/stores': typeof AppStoresRoute
  '/': typeof AppIndexRoute
  '/order/$id': typeof AppOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/gift': typeof AppGiftRoute
  '/_app/order': typeof AppOrderRouteWithChildren
  '/_app/scan': typeof AppScanRoute
  '/_app/stores': typeof AppStoresRoute
  '/_app/': typeof AppIndexRoute
  '/_app/order/$id': typeof AppOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/gift'
    | '/order'
    | '/scan'
    | '/stores'
    | '/order/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/gift'
    | '/order'
    | '/scan'
    | '/stores'
    | '/'
    | '/order/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/gift'
    | '/_app/order'
    | '/_app/scan'
    | '/_app/stores'
    | '/_app/'
    | '/_app/order/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gift': {
      id: '/_app/gift'
      path: '/gift'
      fullPath: '/gift'
      preLoaderRoute: typeof AppGiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order': {
      id: '/_app/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AppOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores': {
      id: '/_app/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order/$id': {
      id: '/_app/order/$id'
      path: '/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof AppOrderIdRouteImport
      parentRoute: typeof AppOrderRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppOrderRouteChildren {
  AppOrderIdRoute: typeof AppOrderIdRoute
}

const AppOrderRouteChildren: AppOrderRouteChildren = {
  AppOrderIdRoute: AppOrderIdRoute,
}

const AppOrderRouteWithChildren = AppOrderRoute._addFileChildren(
  AppOrderRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppGiftRoute: typeof AppGiftRoute
  AppOrderRoute: typeof AppOrderRouteWithChildren
  AppScanRoute: typeof AppScanRoute
  AppStoresRoute: typeof AppStoresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppGiftRoute: AppGiftRoute,
  AppOrderRoute: AppOrderRouteWithChildren,
  AppScanRoute: AppScanRoute,
  AppStoresRoute: AppStoresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
