name: Build iOS

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_ios:
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production
