import type { ImageSourcePropType } from "react-native";

/**
 * assets/game/** require() atlas — Cacique GO.
 * Hessian coffee-bean puppet cutout (Jorge PR brief). Not cream box. Not humanoid Sackboy.
 * Preview craft pack: crema bubbles, highland plants, cork/cardboard/shelf.
 */
export const USE_CRAFT_ART = true;
export const CHARM_RUNNER_PREFERRED = true;

export const GAME_ATLAS_PATHS = {
  runner01: "assets/game/sprites/runner-bean-run.png",
  runner02: "assets/game/sprites/runner-bean-run.png",
  runner03: "assets/game/sprites/runner-bean-run.png",
  runner04: "assets/game/sprites/runner-bean-run.png",
  runnerHop: "assets/game/sprites/runner-bean-hop.png",
  runnerHop01: "assets/game/sprites/runner-bean-hop.png",
  runnerHop02: "assets/game/sprites/runner-bean-hop.png",
  runnerHop03: "assets/game/sprites/runner-bean-hop.png",
  runnerHop04: "assets/game/sprites/runner-bean-hop.png",
  runnerLand: "assets/game/sprites/runner-land.png",
  runnerDeath: "assets/game/sprites/runner-death.png",
  hazardCupStack: "assets/game/sprites/hazard-cup-stack.png",
  hazardGrinder: "assets/game/sprites/hazard-grinder.png",
  hazardKnockbox: "assets/game/sprites/hazard-knockbox.png",
  hazardPortafilter: "assets/game/sprites/hazard-portafilter.png",
  hazardSteam: "assets/game/sprites/hazard-steam.png",
  hazardTamper: "assets/game/sprites/hazard-tamper.png",
  honeyBean: "assets/game/sprites/pickup-honey-bean.png",
  bubble: "assets/game/sprites/bubble.png",
  prizeBubble: "assets/game/sprites/prize-bubble.png",
  coffeeTree: "assets/game/scenery/coffee-tree.png",
  palm: "assets/game/scenery/palm.png",
  banana: "assets/game/scenery/banana.png",
  coconuts: "assets/game/scenery/coconuts.png",
  flamboyan: "assets/game/scenery/flamboyan.png",
  plantain: "assets/game/scenery/plantain.png",
  pineapple: "assets/game/scenery/pineapple.png",
  cacao: "assets/game/scenery/cacao.png",
  dryingBed: "assets/game/scenery/drying-bed.png",
  tinaja: "assets/game/scenery/tinaja.png",
  crate: "assets/game/scenery/crate.png",
  cherries: "assets/game/scenery/cherries.png",
  bunting: "assets/game/scenery/bunting.png",
  coqui: "assets/game/scenery/coqui.png",
  cork: "assets/game/world/cork.jpg",
  cardboard: "assets/game/world/cardboard.jpg",
  shelf: "assets/game/world/shelf.jpg",
  parallax03: "assets/game/world/parallax-03.png",
} as const;

export const GAME_ATLAS: Record<keyof typeof GAME_ATLAS_PATHS, ImageSourcePropType> = {
  runner01: require("../../assets/game/sprites/runner-bean-run.png"),
  runner02: require("../../assets/game/sprites/runner-bean-run.png"),
  runner03: require("../../assets/game/sprites/runner-bean-run.png"),
  runner04: require("../../assets/game/sprites/runner-bean-run.png"),
  runnerHop: require("../../assets/game/sprites/runner-bean-hop.png"),
  runnerHop01: require("../../assets/game/sprites/runner-bean-hop.png"),
  runnerHop02: require("../../assets/game/sprites/runner-bean-hop.png"),
  runnerHop03: require("../../assets/game/sprites/runner-bean-hop.png"),
  runnerHop04: require("../../assets/game/sprites/runner-bean-hop.png"),
  runnerLand: require("../../assets/game/sprites/runner-land.png"),
  runnerDeath: require("../../assets/game/sprites/runner-death.png"),
  hazardCupStack: require("../../assets/game/sprites/hazard-cup-stack.png"),
  hazardGrinder: require("../../assets/game/sprites/hazard-grinder.png"),
  hazardKnockbox: require("../../assets/game/sprites/hazard-knockbox.png"),
  hazardPortafilter: require("../../assets/game/sprites/hazard-portafilter.png"),
  hazardSteam: require("../../assets/game/sprites/hazard-steam.png"),
  hazardTamper: require("../../assets/game/sprites/hazard-tamper.png"),
  honeyBean: require("../../assets/game/sprites/pickup-honey-bean.png"),
  bubble: require("../../assets/game/sprites/bubble.png"),
  prizeBubble: require("../../assets/game/sprites/prize-bubble.png"),
  coffeeTree: require("../../assets/game/scenery/coffee-tree.png"),
  palm: require("../../assets/game/scenery/palm.png"),
  banana: require("../../assets/game/scenery/banana.png"),
  coconuts: require("../../assets/game/scenery/coconuts.png"),
  flamboyan: require("../../assets/game/scenery/flamboyan.png"),
  plantain: require("../../assets/game/scenery/plantain.png"),
  pineapple: require("../../assets/game/scenery/pineapple.png"),
  cacao: require("../../assets/game/scenery/cacao.png"),
  dryingBed: require("../../assets/game/scenery/drying-bed.png"),
  tinaja: require("../../assets/game/scenery/tinaja.png"),
  crate: require("../../assets/game/scenery/crate.png"),
  cherries: require("../../assets/game/scenery/cherries.png"),
  bunting: require("../../assets/game/scenery/bunting.png"),
  coqui: require("../../assets/game/scenery/coqui.png"),
  cork: require("../../assets/game/world/cork.jpg"),
  cardboard: require("../../assets/game/world/cardboard.jpg"),
  shelf: require("../../assets/game/world/shelf.jpg"),
  parallax03: require("../../assets/game/world/parallax-03.png"),
};
